# Generated by Django 6.1.1 on 2026-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=64)),
                ('item_description', models.CharField(max_length=120)),
                ('item_price', models.IntegerField()),
                ('item_stock', models.IntegerField()),
            ],
        ),
    ]
