# Generated by Django 6.1.1 on 2026-09-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
