# Generated by Django 6.1.1 on 2026-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0002_alter_item_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(default='Misc', max_length=120),
        ),
    ]
